/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.mail.internet.ParseException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Jhadith
 */
public class DiaryProgram extends javax.swing.JFrame {

    /**
     * Creates new form DiaryProgram
     */
    public DiaryProgram() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonGroup1.add(rdMasculino);
        buttonGroup1.add(rdFemenino);

        rdMasculino.setActionCommand("Masculino");
        rdFemenino.setActionCommand("Femenino");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        btnCargarFoto = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtImportante = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        lblErrorAcontecimiento = new javax.swing.JLabel();
        btnCargarDatos = new javax.swing.JButton();
        btnMostrarPerfil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdMasculino = new javax.swing.JRadioButton();
        rdFemenino = new javax.swing.JRadioButton();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtComidaFavorita = new javax.swing.JTextField();
        spinEdad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        cboxColor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listMusica = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        lblErrorNombre = new javax.swing.JLabel();
        lblErrorNacimiento = new javax.swing.JLabel();
        lblErrorNumero = new javax.swing.JLabel();
        lblErrorComidaFavorita = new javax.swing.JLabel();
        lblErrorEdad = new javax.swing.JLabel();
        lblErrorColor = new javax.swing.JLabel();
        lblErrorGeneroMusical = new javax.swing.JLabel();
        btnAgendarSalida = new javax.swing.JButton();
        btnLimpiarDatos = new javax.swing.JButton();
        btnDescargarJSON = new javax.swing.JButton();
        btnDescargarCSV = new javax.swing.JButton();
        lblGenero = new javax.swing.JLabel();
        jDFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );

        btnCargarFoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCargarFoto.setText("Cargar Imagen Perfil");

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesion");

        txtImportante.setColumns(20);
        txtImportante.setRows(5);
        jScrollPane2.setViewportView(txtImportante);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Acontecimiento Importante");

        lblErrorAcontecimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorAcontecimiento.setForeground(new java.awt.Color(255, 0, 0));

        btnCargarDatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCargarDatos.setText("Cargar Datos");

        btnMostrarPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarPerfil.setText("Mostrar Perfil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCargarDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion))
                    .addComponent(lblErrorAcontecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCargarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(btnMostrarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargarFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarPerfil)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblErrorAcontecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion)
                    .addComponent(btnCargarDatos))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 280, 650));

        txtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Genero", "Nombre/Apodo", "Fecha Nacimiento", "numero", "Comida Favorita", "Edad", "Color", "Genero Musical", "Importante"
            }
        ));
        jScrollPane1.setViewportView(txtDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 720, 180));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setText("Guardar");
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, 30));

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, -1, 30));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 90, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Genero:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre o Apodo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));

        buttonGroup1.add(rdMasculino);
        rdMasculino.setText("Masculino");
        rdMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(rdMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        buttonGroup1.add(rdFemenino);
        rdFemenino.setText("Femenino");
        jPanel1.add(rdFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Fecha DD-MM-YYYY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Numero de telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));
        jPanel1.add(txtNumeroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Comida Favorita:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 120, -1));

        txtComidaFavorita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComidaFavoritaActionPerformed(evt);
            }
        });
        jPanel1.add(txtComidaFavorita, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 180, -1));
        jPanel1.add(spinEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 100, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Edad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        cboxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Rojo", "Amarillo", "Negro", "Blanco", "Verde", "Rosado", "Naranja", "Celeste", "Morado", "Dorado", "Plateado" }));
        jPanel1.add(cboxColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Color:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 40, -1));

        listMusica.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rock", "Regeton", "Electronica", "Salsa", "Baladas Romanticas", "JRock", "Metal", "Bachatas", "Corridos", "Trap", "Vallenatos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listMusica);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Genero Musical Preferido");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 180, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/escucha (2).png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 70, 80));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 80, 20));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 240, 20));

        lblErrorNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorNombre.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 300, 20));

        lblErrorNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorNacimiento.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 310, 20));

        lblErrorNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorNumero.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 330, 20));

        lblErrorComidaFavorita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorComidaFavorita.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorComidaFavorita, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 260, 20));

        lblErrorEdad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorEdad.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 330, 20));

        lblErrorColor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorColor.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 320, 20));

        lblErrorGeneroMusical.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorGeneroMusical.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorGeneroMusical, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 300, 20));

        btnAgendarSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgendarSalida.setText("Agendar Salida");
        jPanel1.add(btnAgendarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 160, -1));

        btnLimpiarDatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarDatos.setText("Limpiar");
        jPanel1.add(btnLimpiarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 90, 30));

        btnDescargarJSON.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnDescargarJSON.setText("Descargar en JSON");
        btnDescargarJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarJSONActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescargarJSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 170, 20));

        btnDescargarCSV.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnDescargarCSV.setText("Descargar en CSV");
        jPanel1.add(btnDescargarCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 170, 20));

        lblGenero.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 180, 20));
        jPanel1.add(jDFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtComidaFavoritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComidaFavoritaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComidaFavoritaActionPerformed

    private void btnDescargarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarJSONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescargarJSONActionPerformed

    private void rdMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMasculinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaryProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaryProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaryProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaryProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiaryProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAgendarSalida;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCargarDatos;
    public javax.swing.JButton btnCargarFoto;
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnDescargarCSV;
    public javax.swing.JButton btnDescargarJSON;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiarDatos;
    public javax.swing.JButton btnMostrarPerfil;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cboxColor;
    public com.toedter.calendar.JDateChooser jDFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblErrorAcontecimiento;
    public javax.swing.JLabel lblErrorColor;
    public javax.swing.JLabel lblErrorComidaFavorita;
    public javax.swing.JLabel lblErrorEdad;
    public javax.swing.JLabel lblErrorGeneroMusical;
    public javax.swing.JLabel lblErrorNacimiento;
    public javax.swing.JLabel lblErrorNombre;
    public javax.swing.JLabel lblErrorNumero;
    public javax.swing.JLabel lblFoto;
    public javax.swing.JLabel lblGenero;
    public javax.swing.JList<String> listMusica;
    public javax.swing.JRadioButton rdFemenino;
    public javax.swing.JRadioButton rdMasculino;
    public javax.swing.JSpinner spinEdad;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtComidaFavorita;
    public javax.swing.JTable txtDatos;
    public javax.swing.JTextArea txtImportante;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNumeroTelefono;
    // End of variables declaration//GEN-END:variables
}
