/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhadith
 */
public class FaceProgram extends javax.swing.JFrame {

    /**
     * Creates new form FaceProgram
     */
    public FaceProgram() {
        initComponents();
           this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtClave = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        btnRecordar = new javax.swing.JButton();
        btnRecuperar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCorreoR = new javax.swing.JTextField();
        txtUsuarioR = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        lblName5 = new javax.swing.JLabel();
        lblName6 = new javax.swing.JLabel();
        lblName7 = new javax.swing.JLabel();
        txtClaveR = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblErrorUsuario = new javax.swing.JLabel();
        lblErrorClave = new javax.swing.JLabel();
        lblErrorNombre = new javax.swing.JLabel();
        lblErrorApellido = new javax.swing.JLabel();
        lblErrorUsuarioRegistro = new javax.swing.JLabel();
        lblErorClaveRegistro = new javax.swing.JLabel();
        lblErrorCorreo = new javax.swing.JLabel();
        Design = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtClave.setBorder(null);
        jPanel1.add(txtClave);
        txtClave.setBounds(450, 150, 180, 30);

        lblName1.setFont(new java.awt.Font("Couture", 0, 18)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("USUARIO");
        jPanel1.add(lblName1);
        lblName1.setBounds(360, 90, 90, 30);

        lblName2.setFont(new java.awt.Font("Couture", 0, 18)); // NOI18N
        lblName2.setForeground(new java.awt.Color(255, 255, 255));
        lblName2.setText("CLAVE");
        jPanel1.add(lblName2);
        lblName2.setBounds(380, 150, 70, 30);

        btnRecordar.setBackground(new java.awt.Color(51, 0, 51));
        btnRecordar.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        btnRecordar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecordar.setText("RECORDAR USUARIO");
        btnRecordar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecordar);
        btnRecordar.setBounds(640, 90, 230, 30);

        btnRecuperar.setBackground(new java.awt.Color(51, 0, 51));
        btnRecuperar.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        btnRecuperar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecuperar.setText("RECUPERAR CLAVE");
        jPanel1.add(btnRecuperar);
        btnRecuperar.setBounds(640, 150, 230, 30);

        txtApellido.setBorder(null);
        jPanel1.add(txtApellido);
        txtApellido.setBounds(640, 380, 230, 20);

        txtUsuario.setBorder(null);
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(450, 90, 180, 30);

        txtNombre.setBorder(null);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(640, 330, 230, 20);

        txtCorreoR.setBorder(null);
        jPanel1.add(txtCorreoR);
        txtCorreoR.setBounds(640, 530, 230, 20);

        txtUsuarioR.setBorder(null);
        jPanel1.add(txtUsuarioR);
        txtUsuarioR.setBounds(640, 430, 230, 20);

        lblName3.setFont(new java.awt.Font("Couture", 0, 18)); // NOI18N
        lblName3.setForeground(new java.awt.Color(255, 255, 255));
        lblName3.setText("APELLIDO");
        jPanel1.add(lblName3);
        lblName3.setBounds(540, 370, 120, 30);

        lblName4.setFont(new java.awt.Font("Couture", 0, 18)); // NOI18N
        lblName4.setForeground(new java.awt.Color(255, 255, 255));
        lblName4.setText("CORREO");
        jPanel1.add(lblName4);
        lblName4.setBounds(540, 520, 120, 30);

        lblName5.setFont(new java.awt.Font("Couture", 0, 18)); // NOI18N
        lblName5.setForeground(new java.awt.Color(255, 255, 255));
        lblName5.setText("NOMBRE");
        jPanel1.add(lblName5);
        lblName5.setBounds(540, 330, 120, 30);

        lblName6.setFont(new java.awt.Font("Couture", 0, 18)); // NOI18N
        lblName6.setForeground(new java.awt.Color(255, 255, 255));
        lblName6.setText("USUARIO");
        jPanel1.add(lblName6);
        lblName6.setBounds(540, 420, 120, 30);

        lblName7.setFont(new java.awt.Font("Couture", 0, 18)); // NOI18N
        lblName7.setForeground(new java.awt.Color(255, 255, 255));
        lblName7.setText("CLAVE");
        jPanel1.add(lblName7);
        lblName7.setBounds(560, 470, 120, 30);

        txtClaveR.setBorder(null);
        jPanel1.add(txtClaveR);
        txtClaveR.setBounds(640, 480, 230, 20);

        btnSalir.setBackground(new java.awt.Color(51, 0, 51));
        btnSalir.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(660, 600, 200, 30);

        btnIngresar.setBackground(new java.awt.Color(51, 0, 51));
        btnIngresar.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar);
        btnIngresar.setBounds(640, 190, 230, 30);

        btnRegistrar.setBackground(new java.awt.Color(51, 0, 51));
        btnRegistrar.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar);
        btnRegistrar.setBounds(440, 600, 200, 30);

        lblErrorUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorUsuario.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorUsuario);
        lblErrorUsuario.setBounds(370, 120, 260, 20);

        lblErrorClave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorClave.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorClave);
        lblErrorClave.setBounds(370, 190, 260, 20);

        lblErrorNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorNombre.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorNombre);
        lblErrorNombre.setBounds(540, 350, 330, 20);

        lblErrorApellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorApellido.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorApellido);
        lblErrorApellido.setBounds(540, 400, 330, 20);

        lblErrorUsuarioRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorUsuarioRegistro.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorUsuarioRegistro);
        lblErrorUsuarioRegistro.setBounds(540, 450, 330, 20);

        lblErorClaveRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErorClaveRegistro.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErorClaveRegistro);
        lblErorClaveRegistro.setBounds(540, 500, 330, 20);

        lblErrorCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorCorreo.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorCorreo);
        lblErrorCorreo.setBounds(550, 550, 320, 20);

        Design.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/INTERFAZcARA copia.jpg"))); // NOI18N
        jPanel1.add(Design);
        Design.setBounds(0, 0, 920, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecordarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecordarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaceProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaceProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaceProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaceProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaceProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Design;
    public javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnRecordar;
    public javax.swing.JButton btnRecuperar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblErorClaveRegistro;
    public javax.swing.JLabel lblErrorApellido;
    public javax.swing.JLabel lblErrorClave;
    public javax.swing.JLabel lblErrorCorreo;
    public javax.swing.JLabel lblErrorNombre;
    public javax.swing.JLabel lblErrorUsuario;
    public javax.swing.JLabel lblErrorUsuarioRegistro;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtClave;
    public javax.swing.JTextField txtClaveR;
    public javax.swing.JTextField txtCorreoR;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtUsuario;
    public javax.swing.JTextField txtUsuarioR;
    // End of variables declaration//GEN-END:variables
}
