/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author bermu
 */
public class scheduleOutings extends javax.swing.JFrame {

    /**
     * Creates new form AdminUser
     */
    public scheduleOutings() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarSalida = new javax.swing.JButton();
        txtBuscarAmigoSalida = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreSalida = new javax.swing.JTextField();
        lblErrorNombreSalida = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblErrorFechaSalida = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        lblErrorLugarSalida = new javax.swing.JLabel();
        jDFechaSalida = new com.toedter.calendar.JDateChooser();
        btnAgendarSalida = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosSalidas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSalidas = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Couture", 3, 24)); // NOI18N
        jLabel1.setText("AGENDAR SALIDAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 250, -1));

        btnBuscarSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarSalida.setText("Buscar");
        jPanel2.add(btnBuscarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtBuscarAmigoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarAmigoSalidaActionPerformed(evt);
            }
        });
        jPanel2.add(txtBuscarAmigoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 270, -1));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre de la salida:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 293, 20);
        jPanel1.add(txtNombreSalida);
        txtNombreSalida.setBounds(10, 30, 280, 22);

        lblErrorNombreSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorNombreSalida.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lblErrorNombreSalida);
        lblErrorNombreSalida.setBounds(75, 56, 290, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Fecha:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 60, 299, 20);

        lblErrorFechaSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorFechaSalida.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lblErrorFechaSalida);
        lblErrorFechaSalida.setBounds(40, 110, 300, 17);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Lugar:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 120, 299, 20);
        jPanel1.add(txtLugar);
        txtLugar.setBounds(10, 150, 281, 22);

        lblErrorLugarSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrorLugarSalida.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lblErrorLugarSalida);
        lblErrorLugarSalida.setBounds(45, 180, 260, 20);
        jPanel1.add(jDFechaSalida);
        jDFechaSalida.setBounds(10, 80, 280, 22);

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 370, 220));

        btnAgendarSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgendarSalida.setText("Agendar Salida");
        jPanel2.add(btnAgendarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendario.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 137, 137));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 440, -1, -1));

        tblDatosSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Genero", "Nombre/Apodo", "Fecha Nacimiento", "Numero de telefono", "Comida Favorita", "Edad", "Color", "Genero Musical", "Importante"
            }
        ));
        jScrollPane1.setViewportView(tblDatosSalidas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 65, 729, 161));

        tblSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Amigo", "Salida", "Fecha", "Lugar"
            }
        ));
        jScrollPane2.setViewportView(tblSalidas);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 395, 400));

        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarAmigoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarAmigoSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarAmigoSalidaActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scheduleOutings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scheduleOutings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scheduleOutings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scheduleOutings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scheduleOutings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgendarSalida;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnBuscarSalida;
    public javax.swing.JButton btnRegresar;
    public com.toedter.calendar.JDateChooser jDFechaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblErrorFechaSalida;
    public javax.swing.JLabel lblErrorLugarSalida;
    public javax.swing.JLabel lblErrorNombreSalida;
    public javax.swing.JTable tblDatosSalidas;
    public javax.swing.JTable tblSalidas;
    public javax.swing.JTextField txtBuscarAmigoSalida;
    public javax.swing.JTextField txtLugar;
    public javax.swing.JTextField txtNombreSalida;
    // End of variables declaration//GEN-END:variables
}
